modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
    modId="old_school_hardcore"
    version="${file.jarVersion}"
    displayName="Old School Hardcore"
    logoFile="logo.png"
    itemIcon="minecraft:enchanted_golden_apple"
    credits="Darkosto for feature request."
    authors="Gory_Moon"
    description='''
A mod that recreates the "delete" world feature from earlier minecraft versions.

It's integrated into HQM to delete the world when you run out of lives.'''

[[dependencies.old_school_hardcore]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.old_school_hardcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.old_school_hardcore]]
#    modId="hardcorequesting"
#    mandatory=false
#    versionRange="[1.19.4-5.14.0,)"
#    ordering="BEFORE"
#    side="BOTH"

